### ISSUE TITLE
GAP package Congruence - potential name clashes

### ISSUE THREAD

**Issue by olexandr-konovalov** [le-on/ModularGroup#1]
I have just discovered this repository today and had a quick look. Please note that GAP is redistributed with the package Congruence (https://gap-packages.github.io/congruence/), which is not loaded by default. I suggest to check that both packages may be loaded simultaneously - it could happen that a user may need to do that, and also it is the current requirement for packages redistributed with GAP that they should be loadable together - good to keep in mind if you plan to submit this package for the redistribution eventually).

For example, `IsCongruenceSubgroup` is defined there as a category, see https://github.com/gap-packages/congruence/blob/6968f0687c3b2b9e4a2b81a34674013a3a3752c1/lib/cong.gd#L29

**Comment by le-on** [comment]
Thanks for letting me know!
I'm actually aware of this name clash and it's on my To-do-list to resolve it. But as this repository is still in an early phase of development and far from being publishable, it doesn't have the highest priority for me at the moment.
But you are right, before I can submit this as a GAP package, I will have to come up with a different name for ```IsCongruenceSubgroup``` :wink:
